version: '2.4'

services:
  app:
    build:
      context: ./app
    container_name: container-app
    volumes:
      - ../logs/app:/app/logs
      - ..:/app/
    ports:
      - 9000:9000
    working_dir: /app
    command: bash -c 'yarn dev'
    tty: true
    mem_limit: 2500m
    memswap_limit: 3000m
    restart: on-failure:5

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  syslog:
    build: syslog
    container_name: app-syslog
    links:
      - redis
    ports:
      - 601:601
    volumes:
      - ./app/logs:/app/logs
      - ./syslog/config/conf.d.development/:/etc/syslog-ng/conf.d/

  logstash:
    build: logstash
    container_name: app-logstash
    links:
      - redis
    volumes:
      - ./app/logs:/app/logs
      - ./logstash/config/pipeline.development:/usr/share/logstash/pipeline
